#!/usr/bin/env bash
# Spin up (or reuse) the msds682 homework Kafka cluster, create an API key,
# create the Demo 01 topic, and print the values to paste into .env.
#
# Usage:
#   ./setup.sh              # create/reuse cluster + key + topic, print .env values
#   ./setup.sh --write-env  # same, but also write them into ./.env
#
# Requires: confluent CLI (logged in) and jq.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/cluster_config.sh"

WRITE_ENV=false
[[ "${1:-}" == "--write-env" ]] && WRITE_ENV=true

# ---------------------------------------------------------------- preflight ---
command -v confluent >/dev/null || { echo "ERROR: confluent CLI not found. See install note in the chat/README."; exit 1; }
command -v jq        >/dev/null || { echo "ERROR: jq not found. Install with: brew install jq"; exit 1; }
confluent kafka cluster list >/dev/null 2>&1 || { echo "ERROR: not logged in. Run: confluent login"; exit 1; }

# --------------------------------------------------------------- environment ---
if [[ -n "$CONFLUENT_ENV_ID" ]]; then
  confluent environment use "$CONFLUENT_ENV_ID" >/dev/null
else
  # Use the active env; if none is active but exactly one exists, select it.
  if ! confluent kafka cluster list >/dev/null 2>&1; then
    env_count=$(confluent environment list --output json | jq 'length')
    if [[ "$env_count" == "1" ]]; then
      confluent environment use "$(confluent environment list --output json | jq -r '.[0].id')" >/dev/null
    else
      echo "ERROR: no active environment. Set CONFLUENT_ENV_ID in cluster_config.sh"; exit 1
    fi
  fi
fi

# ---------------------------------------------------- create or reuse cluster ---
# jq fallbacks (.field // .altfield) tolerate minor CLI-version key differences.
cluster_id=$(confluent kafka cluster list --output json \
  | jq -r --arg n "$CLUSTER_NAME" '.[] | select(.name == $n) | (.id // .cluster_id)' | head -1)

if [[ -n "$cluster_id" ]]; then
  echo "Reusing existing cluster '$CLUSTER_NAME' ($cluster_id)."
else
  echo "Creating $CLUSTER_TYPE cluster '$CLUSTER_NAME' in $CLOUD/$REGION ..."
  cluster_id=$(confluent kafka cluster create "$CLUSTER_NAME" \
    --cloud "$CLOUD" --region "$REGION" --type "$CLUSTER_TYPE" --output json \
    | jq -r '.id // .cluster_id')
  echo "Created cluster $cluster_id."
fi

# Wait until the cluster is UP and its bootstrap endpoint is published.
echo -n "Waiting for cluster to be ready"
bootstrap=""
for _ in $(seq 1 60); do
  desc=$(confluent kafka cluster describe "$cluster_id" --output json 2>/dev/null || echo '{}')
  status=$(echo "$desc" | jq -r '(.status // "") | ascii_upcase')
  bootstrap=$(echo "$desc" | jq -r '(.endpoint // .kafka_bootstrap_endpoint // "")' | sed 's#^[a-zA-Z_]*://##')
  if [[ "$status" == "UP" && -n "$bootstrap" ]]; then echo " done."; break; fi
  echo -n "."; sleep 5
done
[[ -n "$bootstrap" ]] || { echo; echo "ERROR: cluster did not report a bootstrap endpoint in time."; exit 1; }

# ---------------------------------------------------------------- API key ---
echo "Creating a Kafka API key for $cluster_id ..."
key_json=$(confluent api-key create --resource "$cluster_id" --output json)
api_key=$(echo "$key_json"    | jq -r '.api_key // .key')
api_secret=$(echo "$key_json" | jq -r '.api_secret // .secret')
# Make this key the active one so topic commands can authenticate.
confluent api-key use "$api_key" --resource "$cluster_id" >/dev/null

# ---------------------------------------------------------------- topic ---
if confluent kafka topic list --cluster "$cluster_id" --output json 2>/dev/null \
     | jq -e --arg t "$TOPIC_NAME" 'any(.[]; (.name // .topic_name) == $t)' >/dev/null; then
  echo "Topic '$TOPIC_NAME' already exists."
else
  echo "Creating topic '$TOPIC_NAME' ($PARTITIONS partitions) ..."
  confluent kafka topic create "$TOPIC_NAME" --partitions "$PARTITIONS" --cluster "$cluster_id"
fi

# ---------------------------------------------------------- print .env ---
env_block="# Generated by setup.sh on $(date)
BOOTSTRAP_SERVERS=$bootstrap
SECURITY_PROTOCOL=SASL_SSL
SASL_MECHANISMS=PLAIN
SASL_USERNAME=$api_key
SASL_PASSWORD=$api_secret
DEMO01_TOPIC_NAME=$TOPIC_NAME"

echo
echo "=================================================================="
echo "Cluster is ready. Put these in your .env (secret shown ONCE):"
echo "=================================================================="
echo "$env_block"
echo "=================================================================="

if $WRITE_ENV; then
  printf '%s\n' "$env_block" > "$SCRIPT_DIR/.env"
  chmod 600 "$SCRIPT_DIR/.env"
  echo "Wrote $SCRIPT_DIR/.env (mode 600)."
fi

echo
echo "When you're done with the assignment, run ./teardown.sh to delete it."
